"""Phase 9 live wiring igniter battery (D-159, offline).

Exercises `local/scripts/live_wiring_phase9_igniter.py` fully
offline — the Telegram adapter injected (the REAL `MockTelegramAdapter`
D-075 surface wrapped with a capability profile), the census chained
from the REAL D-158 igniter over the REAL D-157/D-156/D-155/D-154
chain, the ingress through the REAL webhook path (secret verification
+ `parse_update` + `TelegramIngress` dedup), and the sales reply
generated by the REAL Phase 7 `ModelRouter`:

  PASS    — phase8 attestation + verified profile + capability ok +
            clean sandbox sales cycle ⇒ PHASE9_IGNITED with a valid
            `phase9.live_wiring_attestation.v1` (deterministic
            digest);
  TG-01   — phase8 attestation absent / raised / wrong schema /
            wrong verdict / drifted (ledger mismatch) / unrooted /
            broken chain ⇒ refusal with ZERO adapter calls;
  TG-02   — runtime profile mismatch, missing Phase 5/6/7/8 flags,
            seam registry drift ⇒ refusal;
  TG-03   — malformed bot token, capability probe failure, missing
            capabilities, webhook secret mechanism failure, pacer
            failure ⇒ refusal;
  TG-04   — malformed update accepted (ingress contract break),
            unknown intent, session state collision, outbound
            dispatch attempt (SAFETY VIOLATION), cleanup failure ⇒
            refusal;
  TG-05   — exactly one canonical attestation per run (including
            aborts), deterministic digest;
  REDACT  — bot tokens, chat ids, user PII and canaries never reach
            the attestation or audit copies (D-124/D-075);
  AST     — pure igniter core (no network imports, no shell, no
            spawn), adapter/ingress injected only.
"""
from __future__ import annotations

import ast
import json
import pathlib
import sys
import unittest

REPO = pathlib.Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "local" / "scripts"
SRC = REPO / "local" / "src"
for p in (str(REPO / "local"), str(SCRIPTS), str(SRC),
          str(SRC.parent), str(SRC / "security"), str(REPO / "local" / "tests")):
    if p not in sys.path:
        sys.path.insert(0, p)

from canonical.telegram_adapter import (  # noqa: E402
    MockTelegramAdapter, RatePacer, redact,
)
from canonical.telegram_ingress import (  # noqa: E402
    TelegramIngressError, parse_update,
)
from live_wiring_phase8_igniter import (  # noqa: E402
    PHASE8_INCOMPLETE, Phase8Igniter,
)
from live_wiring_phase9_igniter import (  # noqa: E402
    ATTESTATION_SCHEMA, CHAT_ID, CYCLE_ID, LIMITS, PHASE8_ROW_KIND,
    PHASE9_IGNITED, PHASE9_INCOMPLETE, REQUIRED_CAPS, SEAMS,
    SESSION_NS, SYNTHETIC_UPDATE, USER_ID, WEBHOOK_SECRET,
    Phase9Igniter, SessionStore, canonical_hash,
)

ENGINE = SCRIPTS / "live_wiring_phase9_igniter.py"

CANARY = "sk-canaryvalue1234567890abcdef"
BOT_TOKEN = "123456789:AACanaryBotToken0123456789abcdefghijk"
SIGNING_KEY = "stage-f-owner-signing-key-0123456789abcdef"
SESSION = "cutover-session-01"
TARGET = "staging"
SERVICES = ("postgres-ssot", "redis", "app-orchestrator",
            "telemetry-circuit")

MANIFEST = (REPO / "local" / "infra" / "dokploy" /
            "docker-compose.dokploy.yaml").read_text(encoding="utf-8")
TEMPLATE = (REPO / "local" / "infra" / "dokploy" /
            "dokploy_compose_template.yaml").read_text(encoding="utf-8")
ENVELOPE = (REPO / "local" / "infra" / "dokploy" /
            "stage_d_fingerprint.envelope").read_text(encoding="utf-8")


# --- the authentic chain: phase8 attestation via the REAL D-158
# --- engine (which chains D-157 → D-156 → D-155 → D-154) -------------

def real_phase8_attestation(observed_tick=9000):
    """Run the REAL D-158 igniter over the authentic chain with
    in-process fakes (identical to the D-158 battery pass path)."""
    import tests.test_live_wiring_phase8 as t8
    h = t8.Harness(now=observed_tick)
    att = h.run()
    ledger = t8.the_ledger() + [{
        "event_kind": "phase8_live_wiring_attestation",
        "detail": {"attestation_digest": att.attestation_digest,
                   "verdict": att.verdict}}]
    return att.to_dict(), ledger, t8


def real_census() -> dict:
    """The runtime-profile census rows for Phases 5–10, all wired."""
    return {
        "runtime_profile_verified": True,
        "phases": [
            {"phase": n, "name": name, "present": True,
             "verified": True, "wired": True, "detail": "ready"}
            for n, name in ((5, "n8n Foundation"),
                            (6, "Notion Business OS"),
                            (7, "AI Runtime"),
                            (8, "AI Product Manager"),
                            (9, "Instagram"),
                            (10, "AI Sales Agent"))
        ],
    }


def real_router():
    """The REAL Phase 7 router with the caption route (the reply
    generation seam)."""
    from canonical.ai_runtime import (
        ModelRouter, MockAiProvider, RouteTarget)
    return ModelRouter(
        providers={"mock": MockAiProvider()},
        policy={
            "propose_content_idea": RouteTarget(
                "mock", "mock-1", "content_idea_proposal.v1",
                budget_usd=0.50, max_tokens=512, temperature=0.0),
            "generate_caption": RouteTarget(
                "mock", "mock-1", "caption_proposal.v1",
                budget_usd=0.50, max_tokens=512, temperature=0.0),
        },
        budgets={"propose_content_idea": 0.50,
                 "generate_caption": 0.50},
        bucket_capacity=30)


class ProbeTelegramAdapter(MockTelegramAdapter):
    """The REAL MockTelegramAdapter (D-075 dispatch surface, records
    every call without touching a network) wrapped with the TG-03
    capability profile."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.token = BOT_TOKEN
        self.caps = set(REQUIRED_CAPS)

    def capability_profile(self) -> dict:
        return {"bot_token": self.token,
                "bot_username": "engine_sales_sandbox_bot",
                "capabilities": sorted(self.caps)}


# --- the wired harness --------------------------------------------------

_CHAIN: dict = {}

_UNSET = object()  # sentinel: "no override given" (None = absent)


def the_att() -> dict:
    return _CHAIN["att"]


def the_ledger() -> list:
    return _CHAIN["ledger"]


def build_chain() -> None:
    if not _CHAIN:
        att, ledger, _t8 = real_phase8_attestation()
        _CHAIN.update(att=att, ledger=ledger)


class Harness:
    """Fully wired igniter over the authentic phase8 chain; overrides
    swap providers (None = absent)."""

    def __init__(self, now: int = 10000, tg=_UNSET,
                 census=real_census, router=_UNSET,
                 session: SessionStore = None, **overrides):
        build_chain()
        self.now = now
        self.sink: list = []
        self.adapter = ProbeTelegramAdapter() if tg is _UNSET else tg
        self.session = session if session is not None else SessionStore()
        providers = {
            "phase8_provider": the_att,
            "audit_rows": the_ledger,
            "chain_verifier": lambda: {"ok": True,
                                       "rows": len(the_ledger())},
            "census": census,
            "router": real_router() if router is _UNSET else router,
            "tg": self.adapter,
            "session": self.session,
        }
        providers.update(overrides)
        self.igniter = Phase9Igniter(
            clock=lambda: self.now, audit_sink=self.sink.append,
            **providers)

    def run(self):
        return self.igniter.run()


# ===================================================================
# PASS — successful ignition
# ===================================================================

class TestIgnitionPass(unittest.TestCase):

    def test_01_full_ignition_completes(self):
        h = Harness()
        att = h.run()
        self.assertEqual(att.verdict, PHASE9_IGNITED)
        self.assertTrue(att.ignited)
        d = att.to_dict()
        self.assertEqual(d["schema"], ATTESTATION_SCHEMA)
        self.assertEqual(d["schema"],
                         "phase9.live_wiring_attestation.v1")
        self.assertEqual(d["phase8_digest"],
                         canonical_hash(the_att()))
        ids = [c[0] for c in att.checks]
        for rule in ("TG-01", "TG-02", "TG-03", "TG-04", "TG-05"):
            self.assertIn(rule, ids)
        self.assertTrue(all(c[1] for c in att.checks))
        self.assertTrue(d["profile"]["runtime_profile_verified"])
        self.assertTrue(d["profile"]["seams_ok"])
        self.assertTrue(d["capability"]["token_ok"])
        self.assertTrue(d["capability"]["webhook_secret_ok"])
        self.assertTrue(d["capability"]["pacer_ok"])
        self.assertFalse(d["cycle"]["dispatched"])
        self.assertTrue(d["cycle"]["session_cleaned"])

    def test_02_attestation_digest_deterministic(self):
        a1 = Harness(now=10500).run()
        b1 = Harness(now=10500).run()
        self.assertEqual(a1.attestation_digest, b1.attestation_digest)
        self.assertEqual(a1.attestation_digest,
                         canonical_hash(a1.to_dict()))

    def test_03_cycle_steps_recorded(self):
        att = Harness().run()
        steps = att.to_dict()["cycle"]["steps"]
        kinds = [s[0] for s in steps]
        for kind in ("START", "AUTH", "INGRESS_PARSE", "INTENT_ROUTE",
                     "INFER", "STATE_UPDATE", "CLEANUP"):
            self.assertIn(kind, kinds)
        self.assertTrue(all(s[1] for s in steps))
        self.assertEqual(len(att.to_dict()["cycle"]["summary_hash"]),
                         64)

    def test_04_intent_extracted_deterministically(self):
        att = Harness().run()
        steps = {s[0]: s[2] for s in att.to_dict()["cycle"]["steps"]}
        self.assertEqual(steps["INTENT_ROUTE"]["intent"],
                         "order_inquiry")

    def test_05_zero_outbound_dispatch_in_pass_path(self):
        h = Harness()
        att = h.run()
        self.assertFalse(att.to_dict()["cycle"]["dispatched"])
        sent = [c for c in h.adapter.calls
                if isinstance(c, dict)
                and str(c.get("method", "")).startswith("send")]
        self.assertEqual(sent, [])


# ===================================================================
# TG-01 — phase8 attestation refusals (zero adapter calls)
# ===================================================================

class TestTg01Refusals(unittest.TestCase):

    def test_10_missing_phase8_attestation(self):
        h = Harness(phase8_provider=None)
        att = h.run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("absent", att.checks[0][2])
        self.assertEqual(len(h.sink), 1)

    def test_11_provider_raises(self):
        def boom():
            raise RuntimeError("vault offline")
        att = Harness(phase8_provider=boom).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("RuntimeError", att.checks[0][2])

    def test_12_wrong_schema(self):
        att = Harness(phase8_provider=lambda: {
            "schema": "other.v1"}).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("schema", att.checks[0][2])

    def test_13_incomplete_verdict_refused(self):
        bad = dict(the_att())
        bad["verdict"] = PHASE8_INCOMPLETE
        att = Harness(phase8_provider=lambda: bad).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("PHASE8_IGNITED",
                      " ".join(c[2] for c in att.checks))

    def test_14_drifted_digest_refused(self):
        rows = the_ledger()[:-1] + [{
            "event_kind": "phase8_live_wiring_attestation",
            "detail": {"attestation_digest": "c" * 64}}]
        att = Harness(audit_rows=lambda: rows).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("DRIFTED", " ".join(c[2] for c in att.checks))

    def test_15_unrooted_attestation_refused(self):
        att = Harness(audit_rows=lambda: []).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("rooted", " ".join(c[2] for c in att.checks))

    def test_16_broken_chain_refused(self):
        att = Harness(chain_verifier=lambda: {
            "ok": False, "broken_at_seq": 1,
            "reason": "hash mismatch"}).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("not intact",
                      " ".join(c[2] for c in att.checks))

    def test_17_refusal_makes_zero_adapter_calls(self):
        for kwargs in (
                {"phase8_provider": None},
                {"phase8_provider": lambda: {"schema": "x"}},
                {"audit_rows": lambda: []},
                {"chain_verifier": lambda: {"ok": False}}):
            adapter = ProbeTelegramAdapter()
            h = Harness(tg=adapter, **kwargs)
            att = h.run()
            self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
            self.assertEqual(adapter.calls, [])


# ===================================================================
# TG-02 — runtime profile & seams refusals
# ===================================================================

class TestTg02Profile(unittest.TestCase):

    def test_20_unverified_profile_refused(self):
        bad = real_census()
        bad["runtime_profile_verified"] = False
        att = Harness(census=lambda: bad).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("NOT verified",
                      " ".join(c[2] for c in att.checks
                               if c[0] == "TG-02"))

    def test_21_missing_phase8_row_refused(self):
        bad = real_census()
        bad["phases"] = [p for p in bad["phases"]
                         if p["phase"] != 8]
        att = Harness(census=lambda: bad).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("Phase 5/6/7/8",
                      " ".join(c[2] for c in att.checks
                               if c[0] == "TG-02"))

    def test_22_unwired_phase7_refused(self):
        bad = real_census()
        for p in bad["phases"]:
            if p["phase"] == 7:
                p["wired"] = False
        att = Harness(census=lambda: bad).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("VERIFIED+WIRED",
                      " ".join(c[2] for c in att.checks
                               if c[0] == "TG-02"))

    def test_23_seam_registry_drift_refused(self):
        bad_registry = {10: "canonical.nonexistent_module"}
        att = Harness(expected_entry_points=bad_registry).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("registry drift",
                      " ".join(c[2] for c in att.checks
                               if c[0] == "TG-02"))

    def test_24_census_absent_refused(self):
        att = Harness(census=None).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertIn("unavailable",
                      " ".join(c[2] for c in att.checks
                               if c[0] == "TG-02"))


# ===================================================================
# TG-03 — capability & security profile refusals
# ===================================================================

class TestTg03Capability(unittest.TestCase):

    def test_30_malformed_bot_token_refused(self):
        adapter = ProbeTelegramAdapter()
        adapter.token = "not-a-token"
        att = Harness(tg=adapter).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("malformed", blob)

    def test_31_capability_probe_auth_error_refused(self):
        adapter = ProbeTelegramAdapter()

        def forbidden():
            raise PermissionError("401 unauthorized bot")
        adapter.capability_profile = forbidden  # type: ignore
        att = Harness(tg=adapter).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("PermissionError", blob)

    def test_32_missing_capability_refused(self):
        adapter = ProbeTelegramAdapter()
        adapter.caps.discard("webhook_secret")
        att = Harness(tg=adapter).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("missing adapter capabilities", blob)

    def test_33_webhook_secret_mechanism_verified(self):
        # the pass path PROVES the mechanism: wrong header refused,
        # correct header accepted (the run only ignites when both hold)
        att = Harness().run()
        self.assertEqual(att.verdict, PHASE9_IGNITED)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("wrong header refused", blob)

    def test_34_adapter_absent_refused(self):
        att = Harness(tg=None).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("unavailable", blob)

    def test_35_no_capability_profile_refused(self):
        att = Harness(tg=MockTelegramAdapter()).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-03")
        self.assertIn("capability profile", blob)

    def test_36_rate_pacer_envelope_proven(self):
        pacer = RatePacer(global_rate=LIMITS["global_rate_per_sec"],
                          per_chat_rate=LIMITS["per_chat_rate_per_sec"])
        waits = [pacer.acquire("sandbox", now_s=i * 0.1)
                 for i in range(6)]
        self.assertTrue(all(w >= 0.0 for w in waits))
        self.assertTrue(any(w > 0.0 for w in waits))


# ===================================================================
# TG-04 — synthetic sales cycle refusals
# ===================================================================

class TestTg04Cycle(unittest.TestCase):

    def test_40_malformed_updates_fail_closed_locally(self):
        for bad in (b"not json", b"{}", b"[1,2]", b'{"update_id": -1}'):
            with self.assertRaises(TelegramIngressError):
                parse_update(bad)

    def test_41_router_absent_refused(self):
        att = Harness(router=None).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-04")
        self.assertIn("fail closed", blob)

    def test_42_router_without_reply_route_refused(self):
        import tests.test_live_wiring_phase7 as t7
        att = Harness(router=t7.real_router()).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-04")
        self.assertIn("no generate_caption route", blob)

    def test_43_session_state_collision_refused(self):
        store = SessionStore()
        key = SESSION_NS + "9001"
        store.set(key, {"intent": "order_inquiry"})
        with self.assertRaises(Exception):
            store.set(key, {"intent": "price_inquiry"})

    def test_44_session_scope_violation_refused(self):
        store = SessionStore()
        with self.assertRaises(Exception):
            store.set("etc/passwd", {})
        with self.assertRaises(Exception):
            store.get("etc/passwd")

    def test_45_outbound_dispatch_is_safety_violation(self):
        adapter = ProbeTelegramAdapter()

        def sneaky_send(chat_id, text, parse_mode=""):
            return adapter.send_text.__wrapped__(adapter, chat_id,
                                                 text, parse_mode) \
                if hasattr(adapter.send_text, "__wrapped__") else \
                MockTelegramAdapter.send_text(adapter, chat_id, text,
                                              parse_mode)
        adapter.capability_profile = lambda: {
            "bot_token": BOT_TOKEN,
            "bot_username": "engine_sales_sandbox_bot",
            "capabilities": sorted(REQUIRED_CAPS)}
        # simulate a rogue dispatch DURING the cycle: patch set() so a
        # send happens right after STATE_UPDATE
        orig_send = MockTelegramAdapter.send_text
        calls = adapter.calls

        def send_once(*a, **kw):
            return orig_send(*a, **kw)
        # dispatch directly so the adapter log records a send
        adapter.send_text(CHAT_ID, "unsolicited")
        att = Harness(tg=adapter).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-04")
        self.assertIn("SAFETY VIOLATION", blob)
        self.assertFalse(att.to_dict()["cycle"]["dispatched"])

    def test_46_cleanup_failure_refused(self):
        class DirtyStore(SessionStore):
            def delete(self, key):
                return False  # refuses to clean
        att = Harness(session=DirtyStore()).run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-04")
        self.assertIn("cleanup failed", blob)

    def test_47_cycle_deterministic_summary(self):
        s1 = Harness().run().to_dict()["cycle"]["summary_hash"]
        s2 = Harness().run().to_dict()["cycle"]["summary_hash"]
        self.assertEqual(s1, s2)

    def test_48_unknown_intent_text_refused(self):
        # a fixture whose text matches no intent must refuse; drive
        # the REAL cycle with a synthetic update carrying unrelated
        # text (monkeypatched fixture for this probe only)
        from live_wiring_phase9_igniter import SYNTHETIC_UPDATE as orig
        import live_wiring_phase9_igniter as eng
        unrelated = dict(orig)
        unrelated["message"] = dict(orig["message"],
                                    text="hello world")
        h = Harness()
        saved = eng.SYNTHETIC_UPDATE
        eng.SYNTHETIC_UPDATE = unrelated
        try:
            att = h.run()
        finally:
            eng.SYNTHETIC_UPDATE = saved
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        blob = " ".join(c[2] for c in att.checks if c[0] == "TG-04")
        self.assertIn("unknown intent", blob)
        # fail-closed hygiene: the session store is still cleaned
        self.assertTrue(att.to_dict()["cycle"]["session_cleaned"])


# ===================================================================
# TG-05 — emission contract
# ===================================================================

class TestTg05Emission(unittest.TestCase):

    def test_50_exactly_one_attestation_per_run(self):
        h = Harness()
        att = h.run()
        self.assertEqual(len(h.sink), 1)
        self.assertEqual(h.sink[0]["schema"], ATTESTATION_SCHEMA)
        self.assertEqual(h.sink[0]["verdict"], att.verdict)

    def test_51_abort_still_emits_attestation(self):
        h = Harness(phase8_provider=None)
        att = h.run()
        self.assertEqual(att.verdict, PHASE9_INCOMPLETE)
        self.assertEqual(len(h.sink), 1)

    def test_52_digest_covers_every_field(self):
        att = Harness().run()
        d = att.to_dict()
        for key in ("schema", "verdict", "phase8_digest",
                    "manifest_sha256", "profile", "capability",
                    "cycle", "checks", "observed_tick"):
            self.assertIn(key, d)


# ===================================================================
# REDACT — zero secret leakage (D-124/D-075)
# ===================================================================

class TestRedaction(unittest.TestCase):

    def test_60_no_tokens_or_canaries_in_outputs(self):
        h = Harness()
        att = h.run()
        blob = json.dumps(att.to_dict()) + json.dumps(h.sink)
        for secret in (BOT_TOKEN, CANARY, SIGNING_KEY, WEBHOOK_SECRET):
            self.assertNotIn(secret, blob)

    def test_61_adapter_redacts_bot_token_material(self):
        text = redact(f"failed bot{BOT_TOKEN} call")
        self.assertNotIn(BOT_TOKEN, text)
        self.assertIn("[REDACTED]", text)

    def test_62_no_chat_or_user_ids_in_outputs(self):
        att = Harness().run()
        blob = json.dumps(att.to_dict()) + json.dumps(Harness().sink)
        self.assertNotIn(str(CHAT_ID), blob)
        self.assertNotIn(str(USER_ID), blob)

    def test_63_no_message_text_in_outputs(self):
        att = Harness().run()
        blob = json.dumps(att.to_dict()) + json.dumps(Harness().sink)
        # the customer text and the reply text appear only as hashes
        self.assertNotIn(SYNTHETIC_UPDATE["message"]["text"], blob)
        self.assertNotIn("caption_fa", blob)

    def test_64_deep_redact_runs_on_emitted_records(self):
        h = Harness()
        att = h.run()
        row = h.sink[0]
        self.assertEqual(row["phase8_digest"], att.phase8_digest)
        self.assertEqual(row["manifest_sha256"],
                         att.manifest_sha256)


# ===================================================================
# AST — purity audits
# ===================================================================

class TestAstPurity(unittest.TestCase):

    def setUp(self):
        self.tree = ast.parse(ENGINE.read_text(encoding="utf-8"))

    def test_70_no_forbidden_imports_in_engine(self):
        banned = {"socket", "http", "urllib", "requests", "ftplib",
                  "smtplib", "asyncio", "subprocess", "shutil", "pty",
                  "commands", "os"}
        for node in ast.walk(self.tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.split(".")[0]
                    self.assertNotIn(root, banned,
                                     f"forbidden import {alias.name}")
            elif isinstance(node, ast.ImportFrom):
                root = (node.module or "").split(".")[0]
                self.assertNotIn(root, banned,
                                 f"forbidden import from {node.module}")

    def test_71_no_shell_or_spawn_calls(self):
        for node in ast.walk(self.tree):
            if isinstance(node, ast.Call):
                fn = node.func
                name = getattr(fn, "attr", getattr(fn, "id", ""))
                self.assertNotIn(name,
                                 ("system", "popen", "Popen",
                                  "spawn", "spawnl", "spawnv"),
                                 f"forbidden call {name}")

    def test_72_injected_dependencies_only(self):
        src = ENGINE.read_text(encoding="utf-8")
        self.assertIn("tg: Optional[Any]", src)
        self.assertIn("router: Optional[Any]", src)
        self.assertIn("def _load", src)

    def test_73_sandbox_only_guarantee_in_source(self):
        src = ENGINE.read_text(encoding="utf-8")
        self.assertIn("SAFETY VIOLATION", src)
        self.assertIn("SESSION_NS", src)
        self.assertNotIn("send_text(", src)


if __name__ == "__main__":
    unittest.main()
